### ISSUE TITLE
Can't use `Protocol`

### ISSUE THREAD

**Issue by yingmu52** [SwiftDocOrg/SwiftSemantics#19]
![image](https://user-images.githubusercontent.com/1755380/126459917-dee4f72e-4ee0-4fa2-b01c-54e51aeaf29c.png)

I was able to use `[Class]`, `[Structure]` but not `[Protocol]` or `[SwiftSemantics.Protocol]` for some reason, any idea will be appreciated

**Comment by mattt** [comment]
I'm not sure what other modules you're importing, but this looks like a name collision (though usually that can be resolved by using a fully-qualified name like `SwiftSemantics.Protocol`...)

What if you add the following line after the last `import` statement?

```swift
import struct SwiftSemantics.Protocol`
```

**Comment by yingmu52** [comment]
Awesome, this does resolve the name collision, many thanks @mattt 

https://github.com/yingmu52/swift-project-analyzer/commit/ba3437456d709337af77c66df42b514d0479f102
